name: Pygame Build
run-name: Pygame Build is out GitHub Actions 🚀
on: push
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Check Pylint
        run: |
          pylint .

